name: Continuous Integration

# this is trigger CI on push and PR for main branch only
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# this is trigger CI on push and PR for main, dev, master branch only
# on:
#   push:
#     branches: [ main, dev, master ]
#   pull_request:
#     branches: [ main, dev, master]

# this is trigger CI on all kinds of branches and PRs
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Check formatting (non-destructive)
        run: npm run format:check

      # - name: Run format check
      #   run: npm run format

      # - name: Check commit messages
      #   uses: wagoid/commitlint-github-action@v3
      #   with:
      #     configFile: commitlint.config.cjs

      # This is the best-rules before commiting
      # - name: Check commit messages
      #   run: |
      #     from_commit=$(git rev-list HEAD | tail -n 1)
      #     npx commitlint --from=$from_commit --to=HEAD --config commitlint.config.cjs
      - name: Check latest commit message
        run: npx commitlint --from=HEAD~1 --to=HEAD --config commitlint.config.cjs
