name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your main development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to prod url- Github Pages
        # main is the branch name where new code is pushed
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.


      # - name: Deploy to GitHub Pages (dev)
      #   if: github.ref == 'refs/heads/develop'
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #     with:
      #       branch: dev-gh-pages
      #       folder: dist
# TO KNOW
# it might through permission error during deployment,
# go the repo settings, Action > General > Workflow permissions
# and select Read and Write permissions
# click save,
# re-run jobs and it should fix the error

# uses: peaceiris/actions-gh-pages@v3
# with:
#   github_token: ${{ secrets.GITHUB_TOKEN }}
#   publish_dir: ./dist
# publish_branch: prod-gh-pages  // by default it will create gh-pages branch and push everything of dist folder inside it.

# - name: Deploy to dev url
#   if: github.ref == 'refs/heads/develop'
#   uses: peaceiris/actions-gh-pages@v3
#   with:
#     github_token: ${{ secrets.GITHUB_TOKEN }}
#     publish_dir: ./dist
#     # publish_branch: dev-gh-pages

# How to get the uses
# Go to github marketplace and search for peaceiris/actions-gh-pages
